server:
  port: 8081

app:
  name: "ToDo-Manager-MVP"
  version: "1.0.0-SNAPSHOT"
  description: "Spring Boot Homework Application"

spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    com.example.todo: DEBUG

---

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    com.example.todo: ERROR